googleAnalytics: UA-199278356-1
baseURL : https://francoiducat.github.io
languageCode :  en-us
title : FDUCAT Notebook
theme: book

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo: true

params:
  BookRepo: https://github.com/francoiducat/francoiducat.github.io.sources
  BookCommitPath: commit
  BookDateFormat: Jan 2, 2006
