baseURL : https://francoiducat.github.io
languageCode :  en-us
title : FDUCAT Notebook
theme: book

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics: G-PXY5L88X6W

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo: true

params:
  BookRepo: https://github.com/francoiducat/francoiducat.github.io.sources
  BookCommitPath: commit
  BookDateFormat: Jan 2, 2006
