baseURL : https://francoiducat.github.io
languageCode :  en-us
title : FDUCAT Notebook
theme: book

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics: G-SQK9KWNWZY

# Set source repository location.
# Used for 'Last Modified' and 'Edit this page' links.
BookRepo : https://github.com/francoiducat/francoiducat.github.io.sources

# Specifies commit portion of the link to the page's last modified commit hash for 'doc' page
# type.
# Required if 'BookRepo' param is set.
# Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
# Github uses 'commit', Bitbucket uses 'commits'
BookCommitPath: commit

# Enable 'Edit this page' links for 'doc' page type.
# Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
# Path must point to the site directory.
BookEditPath: edit/main

# (Optional, default January 2, 2006) Configure the date format used on the pages
# - In git information
# - In blog posts
BookDateFormat: Jan 2, 2006
